version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Running quality checks
      - echo "QUALITY GATE PASSED"

artifacts:
  files:
    - '**/*'
